# Generated by Django 4.2.24 on 2025-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='year',
            field=models.CharField(default='2025', max_length=4, verbose_name='年份'),
        ),
    ]
